name: Python CI with Log Processing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Setting up..."

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests and capture logs
      run: |
        echo "Running tests..." | tee logs.txt
        python main.py 2>&1 | tee -a logs.txt
        echo $? > exit_code.txt  # Capture exit code

    - name: Process logs after failure
      run: |
        if [[ $(cat exit_code.txt) -ne 0 ]]; then
          echo "Analyzing logs due to failure..."
          python process_log.py logs.txt
        fi

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs.txt
