name: Analyze Logs on Failure

on:
  workflow_dispatch:  # Allows manual trigger
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  analyze-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          python main.py
          exit 1
        id: run-tests

      # Capture logs from the GitHub Actions runner output and save to a file
      - name: Save logs on failure
        if: failure()
        run: |
          echo "Saving logs..."
          # Capture workflow logs and save them to a file
          LOG_FILE=$GITHUB_WORKSPACE/logs.txt
          
          echo "Captured Logs:" > $LOG_FILE
          echo "Step ID: run-tests" >> $LOG_FILE
          echo "-------------------" >> $LOG_FILE
          
          # Use GitHub Actions command to read logs
          cat $GITHUB_WORKSPACE/logs.txt >> $LOG_FILE || echo "No additional logs found."
          
          # Capture any environment or workflow-specific variables if necessary
          echo "Environment Variables:" >> $LOG_FILE
          env >> $LOG_FILE

      # Send logs to Python script
      - name: Analyze logs using Python script
        if: failure()
        run: |
          python process_logs.py "$GITHUB_WORKSPACE/logs.txt"
