name: Analyze Logs on Failure

on:
  workflow_dispatch:  # Manual trigger
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  analyze-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          python main.py
          exit 1
        id: run-tests

      # Capture logs from the test step and save to a file
      - name: Capture logs and save to a file
        if: failure()
        run: |
          echo "Saving logs..."

          LOG_FILE=$GITHUB_WORKSPACE/logs.txt

          # Capture logs from each previous step, particularly the 'run-tests' step
          echo "------------------- Step: run-tests -------------------" >> $LOG_FILE
          echo "Output from run-tests step:" >> $LOG_FILE
          cat $GITHUB_WORKSPACE/_temp/logs.txt >> $LOG_FILE || echo "No logs captured from tests."

          # You can also capture the job's debug logs, if any
          echo "------------------- Environment and Debug Info -------------------" >> $LOG_FILE
          env >> $LOG_FILE

      # Send logs to Python script for analysis
      - name: Analyze logs using Python script
        if: failure()
        run: |
          python process_logs.py "$GITHUB_WORKSPACE/logs.txt"
