name: Analyze Logs on Failure

on:
  workflow_dispatch:  # Manual trigger
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  analyze-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          python main.py
          exit 1
        id: run-tests

      # Capture logs from the GitHub Actions runner output and save to a file
      - name: Capture entire job logs
        if: failure()
        run: |
          echo "Saving logs..."
          
          # GitHub captures step output and stores them in a temporary log file
          LOG_FILE=$GITHUB_WORKSPACE/logs.txt
          
          # Add a header to the log file
          echo "Captured Logs:" > $LOG_FILE
          
          # Output the logs of all previous steps to the log file
          echo "------------------- Step: run-tests -------------------" >> $LOG_FILE
          cat $GITHUB_STEP_SUMMARY >> $LOG_FILE
          
          # Add the full runner logs (debug output) to the file
          echo "------------------- Runner Logs -------------------" >> $LOG_FILE
          cat /home/runner/work/_temp/_runner_file_commands/*.log >> $LOG_FILE || echo "No runner logs found." >> $LOG_FILE

      # Send logs to Python script for analysis
      - name: Analyze logs using Python script
        if: failure()
        run: |
          python process_logs.py "$GITHUB_WORKSPACE/logs.txt"
