name: Python CI with Log Processing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Setting up..."

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests and capture logs
      run: |
        echo "Running tests..." | tee logs.txt
        python main.py 2>&1 | tee -a logs.txt
      # continue-on-error: true  # Continue workflow even if the step fails

    - name: Process logs after failure
      if: failure()  # Only runs if the previous steps failed
      run: |
        echo "Analyzing logs due to failure..."
        python process_log.py logs.txt
