name: Python CI with Log Processing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - name: Set up job
      run: echo "Setting up..."

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests and capture logs
      run: |
        pip install langchain-google-genai
        echo "Running tests..." | tee logs.txt
        python main.py >> logs.txt 2>&1  # Redirect both stdout and stderr to logs.txt
        echo $? > exit_code.txt  # Capture exit code

    - name: Process logs after failure
      if: failure()
      run: |
          echo "Analyzing logs due to failure..."
          echo "SENDER_PASSWORD=${{env.SENDER_PASSWORD}}" >> $GITHUB_ENV
          python process_logs.py logs.txt

    - name: Display logs for debugging
      run: cat logs.txt
      if: failure()  # Only display logs if previous steps failed
