name: Python CI with Log Processing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Setting up..."

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests and capture logs
      run: |
        echo "Running tests..." | tee logs.txt
        python main.py >> logs.txt 2>&1  # Redirect both stdout and stderr to logs.txt
        echo $? > exit_code.txt  # Capture exit code

    - name: Process logs after failure
      if: failure()
      run: |
          echo "Analyzing logs due to failure..."
          python process_log.py logs.txt
        fi

    - name: Display logs for debugging
      run: cat logs.txt
      if: failure()  # Only display logs if previous steps failed
